# Spring Boot configuration
spring:

  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://185.22.62.114:5432/gorzdrav
    username: postgres
    password: elkin25pass

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO

# Server configuration
server:
  port: 8080
  sessionTimeout: 30

# parser configuration
parser:
  specialityUpdateTimePeriodInSec: 300
  lpuUpdateTime: "22:00"

email:
  username: covvacmailsender@gmail.com
  password: mail5cov1sender!
