# Spring Boot configuration
spring:

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://185.22.62.114:5432/gorzdrav
    username: postgres
    password: elkin25pass

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

# Server configuration
server:
  port: 8080
  sessionTimeout: 30
